



PATCH https://nfhojhncajsquwwzzmrn.supabase.co/rest/v1/profiles?id=eq.d71733ae-cf0a-4e3a-bf4d-3bf7eab097a8
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5maG9qaG5jYWpzcXV3d3p6bXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzA2NTEsImV4cCI6MjA2MDMwNjY1MX0.OmgFswsZ8NtxTcasr4MXy8mT4u_43aP_QqaZIXA_KlE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImV3WVB1TE0zbmpud2NGS0UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25maG9qaG5jYWpzcXV3d3p6bXJuLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkNzE3MzNhZS1jZjBhLTRlM2EtYmY0ZC0zYmY3ZWFiMDk3YTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ5MTEzMzA3LCJpYXQiOjE3NDkxMDk3MDcsImVtYWlsIjoiYW51cGFtdGhha3VyMDU4QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJhbnVwYW10aGFrdXIwNThAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiQW51cGFtIFRoYWt1ciJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ5MDU2MTA5fV0sInNlc3Npb25faWQiOiI1NWE1MTE1Mi03MWQ3LTRhNGUtYTI2ZS05OGE0ZWE4NjU2OGMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.q96WIR6UDXUNHKkBBA4tTI0zBD4VHrus4vUQRH5fAjk
Content-Type: application/json
Prefer: return=representation

{
  "username": "Anupam Thakur"
}

